const PRODUCTS = [
  {
    category: 'cctv',
    categoryLabel: 'Explosion Proof CCTV Monitoring System',
    categoryIcon: 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/f6035baa8_image.png',
    items: [
      {
        name: 'Explosion Proof Cylindrical Camera',
        desc: '· Explosion proof, shell, made of 304 stainless steel material, waterproof and corrosion-resistant; · High transparency explosion-proof glass with high strength and no blurring; · Adopting double-layer sealing treatment, the outdoor protection reaches IP68 professional level, fearless of harsh outdoor environments; · Supports automatic ICR day and night mode; · Support POE power supply; · Designed with 4000V lightning protection and surge protection, the product is more stable and improves its service life..',
        params: 'ExdIIBT6 Gb | IP68 | 4.8-120mm | Optical X25 | DC12V/POE | 10W | 4kg',
        image: 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/933620b79_image.png',
      },
      {
        name: 'Explosion Proof PTZ Integrated Camera',
        desc: '· Explosion proof, shell, made of 304 stainless steel material, waterproof and corrosion-resistant; · High transparency explosion-proof glass with high strength and no blurring; · High hardness gear combination rotating mechanism, durable and reliable; · Adopting double-layer sealing treatment, the outdoor protection reaches IP68 professional level, fearless of harsh outdoor environments; · Supports automatic ICR day and night mode; · Remote control camera PTZ horizontal 0 ° -360 °, vertical ± 90 ° adjustment; · Designed with 4000V lightning protection and surge protection, the product is more stable and improves its service life..',
        params: 'ExdIIBT6 Gb | IP68 | 4.0MP | PTZ 360° | AC24V | 35W | 21kg',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&q=80',
        pdfPage: 2,
      },
      {
        name: 'Explosion Proof Ball Type Camera',
        desc: '· Explosion proof, shell, made of 304 stainless steel material, waterproof and corrosion-resistant; · High hardness gear combination rotating mechanism, durable and reliable; · High transparency explosion-proof glass with high strength and no blurring; · Adopting double-layer sealing treatment, the outdoor protection reaches IP68 professional level, fearless of harsh outdoor environments; · Supports automatic ICR day and night mode; · Designed with 4000V lightning protection and surge protection, the product is more stable and improves its service life..',
        params: 'ExdIIBT6 Gb | IP68 | 2.0/4.0MP | Optical X22 | AC24V | 35W | 18kg',
        pdfPage: 3,
      },
      {
        name: 'Explosion Proof Hemispherical Camera',
        desc: '· · Explosion proof, with a shell made of 304 stainless steel material that is waterproof and corrosion-resistant; · High hardness gear combination rotating mechanism, durable and reliable; · High transparency explosion-proof glass with high strength and no blurring; · Adopting double-layer sealing treatment, the outdoor protection reaches IP68 professional level, fearless of harsh outdoor environments; · Supports automatic ICR day and night mode; · Designed with 4000V lightning protection and surge protection, the product is more stable and improves its service life.',
        params: 'ExdIIBT6 Gb | IP68 | 2.0MP | 4mm focal | DC12V/POE | 20W | 1.5kg',
        pdfPage: 4,
      },
      {
        name: 'Explosion Proof Infrared Cylindrical Camera',
        desc: 'IR illumination distance 70 meters, IP68, 4.0MP, Optical X25, 304 stainless steel, -30°C~+65°C.',
        params: 'ExdIIBT6 Gb | IP68 | 4.0MP | IR 70m | DC12V/POE | 12W | 4.5kg',
        pdfPage: 5,
      },
      {
        name: 'Explosion Proof PTZ Integrated Infrared Camera',
        desc: 'IR 70m range, PTZ 360° horizontal ±90° vertical, IP68, 4.0MP, AC24V/AC220V, 28kg.',
        params: 'ExdIIBT6 Gb | IP68 | 4.0MP | IR PTZ | AC24V/AC220V | 35W | 28kg',
        pdfPage: 6,
      },
      {
        name: 'Explosion Proof Display',
        desc: 'HD industrial display, auto brightness adjustment (300-1000 cd/m²), 1920×1080, HDMI, IP54, visible in direct sunlight.',
        params: 'ExdIIBT6 Gb | IP54 | 1920×1080 | HDMI | DC12V | 45W | 21kg',
        pdfPage: 7,
      },
      {
        name: 'Explosion Proof Control Keyboard',
        desc: 'RS485 bus interface, backlit button design, 304 stainless steel electrophoretic shell, key lifespan ≥2 million triggers.',
        params: 'Exia IIC T6Ga | IP45 | RS485 | DC5V | 100×168×50mm',
        pdfPage: 8,
      },
      {
        name: 'Explosion Proof Network Bridge',
        desc: '25dBi dual polarization high gain antenna, 100Mbps wireless rate, IP67, distance ≥5km.',
        params: 'ExdbIIB T6 Gb | IP67 | 100Mbps | ≥5km | DC12V/POE',
        pdfPage: 9,
      },
      {
        name: 'Explosion-Proof Control Box',
        desc: 'Supports up to 26 input cameras, 16 channels, H.265/H.264, 4000V lightning protection, IP54.',
        params: 'ExdIIBT6 Gb | IP54 | 16ch | H.265/H.264 | AC85-245V | 85W | 32kg',
        pdfPage: 10,
      },
    ],
  },
  {
    category: 'intercom',
    categoryLabel: 'Explosion Proof Digital Intercom System',
    categoryIcon: 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/81693c0a9_image.png',
    items: [
      {
        name: 'Explosion Proof Digital Telephone Station',
        desc: 'Zinc aluminum alloy, SIP2.0, full duplex, G.711/G.729/G.722/G.726, bridging mode, earthquake and impact resistant.',
        params: 'Exd Ib IIC T6 Gb | SIP2.0 | DC48V | 24W | -30°C~65°C | 240×350×140mm',
        pdfPage: 11,
      },
      {
        name: 'Explosion Proof Digital Telephone Station – Noise Reduction Version',
        desc: 'Noise reduction version, SIP2.0, full duplex, G.168 echo cancellation, zinc aluminum alloy shell, backlit keys.',
        params: 'Exd Ib IIC T6 Gb | SIP2.0 | DC48V | 24W | -30°C~65°C | 240×350×140mm',
        pdfPage: 12,
      },
      {
        name: 'Explosion Proof Speaking Station',
        desc: 'One-click quick call, full duplex hands-free intercom, outdoor explosion-proof trigger buttons, SIP2.0 protocol.',
        params: 'Exd Ib IIC T6 Gb | SIP2.0 | DC48V | 24W | -30°C~65°C | 240×350×140mm',
        pdfPage: 13,
      },
      {
        name: 'Explosion Proof Digital Intercom Control Box',
        desc: '7 DDS quick call buttons, RF interference shielding, noise suppression, stainless steel electrophoresis shell, SIP2.0.',
        params: 'Exia IIC T6Gm | IP45 | DC48V | 15W | -30°C~65°C | 110×136×95mm',
        pdfPage: 14,
      },
      {
        name: 'Explosion Proof Communication Control Box',
        desc: '9 channels, manages 200+ peripheral stations, SIP protocol, single/group call, broadcasting, recording, IP54.',
        params: 'ExdIIBT6 Gb | IP54 | 9ch | AC85-245V | 85W | 32kg',
        pdfPage: 15,
      },
      {
        name: 'Regular Network Telephone',
        desc: '7-inch color screen, SIP2.0, HD hands-free, H.264 video, 3-party conference, 1000Mbps, 500h recording.',
        params: 'Android 6.0 | 7" 1024×600 | 4 SIP accounts | POE/5V-2A',
        pdfPage: 16,
      },
      {
        name: 'Wireless Handheld Network Telephone',
        desc: '4G+VOIP dual mode, color display, HD hands-free, 3-party conference, 1600mAH battery, 5h talk time.',
        params: '240×320 | 3 SIP lines | Dual SIM | DC5V 1A',
        pdfPage: 17,
      },
      {
        name: 'Explosion Proof Speaker',
        desc: '360° lossless broadcasting, stainless steel wire mesh, IP66, 50W, 250Hz–3400Hz, public address and paging.',
        params: 'ExdICT6 Gb | IP66 | 8Ω | 50W | 250Hz-3400Hz | -20°C~+65°C | 5kg',
        pdfPage: 18,
      },
      {
        name: 'Anti Noise And Noise Reduction Pavilion',
        desc: 'Polyethylene plastic, polyurethane soundproof lining, -24dB sound insulation, suitable for heavy-duty industrial phones up to 60kg.',
        params: '-24dB | 780×680×500mm | 22kg | Indoor/Outdoor/Sea',
        pdfPage: 19,
      },
      {
        name: 'Stainless Steel Telephone Booth',
        desc: '304 stainless steel, anti-static spray paint, noise reducing cotton lining, fixed upright poles, corrosion resistant.',
        params: '420×520×295mm | Rainproof height 173cm | 27kg',
        pdfPage: 20,
      },
    ],
  },
  {
    category: 'other',
    categoryLabel: 'Other Project Products',
    categoryIcon: 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/abaaf37ab_image.png',
    items: [
      {
        name: 'Ring Tilt Anti-Collision Device',
        desc: '10.4" LCD, real-time hook height display, anti-collision with sound & light alarm, brake output DC24V, SCR data collection.',
        params: 'Height -2~60m | Precision ±1% | AC220V 50HZ | -30°C~65°C',
        pdfPage: 21,
      },
      {
        name: 'Monitoring Device For Lifting Up The Drilling Rig Frame',
        desc: '12" LCD, real-time animated mast lifting display, deadline pressure alarm, IP67, built-in rechargeable battery.',
        params: 'IP67 | 12" 1280×768 | DC12V/DC24V | -30°C~+65°C | 0-4500KN',
        pdfPage: 22,
      },
    ],
  },
];

// Product images
const PRODUCT_IMAGES = {
  'Explosion Proof Cylindrical Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/bd645edc1_generated_image.png',
  'Explosion Proof PTZ Integrated Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/feaa5d307_generated_image.png',
  'Explosion Proof Ball Type Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/8fa52cbbd_generated_image.png',
  'Explosion Proof Hemispherical Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/0f682f30f_generated_image.png',
  'Explosion Proof Infrared Cylindrical Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/cae4aa41e_generated_image.png',
  'Explosion Proof PTZ Integrated Infrared Camera': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/55c0bef7a_generated_image.png',
  'Explosion Proof Display': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/a5a56d897_generated_image.png',
  'Explosion Proof Control Keyboard': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/b175676b4_generated_image.png',
  'Explosion Proof Network Bridge': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/bd41cf129_generated_image.png',
  'Explosion-Proof Control Box': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/e47e0d1ed_generated_image.png',
  'Explosion Proof Digital Telephone Station': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/922bcfa8b_generated_image.png',
  'Explosion Proof Digital Telephone Station – Noise Reduction Version': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/1e261ffc2_generated_image.png',
  'Explosion Proof Speaking Station': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/049e45e6b_generated_image.png',
  'Explosion Proof Digital Intercom Control Box': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/63891bb48_generated_image.png',
  'Explosion Proof Communication Control Box': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/7e759b91e_generated_image.png',
  'Regular Network Telephone': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/1282e89cf_generated_image.png',
  'Wireless Handheld Network Telephone': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/71b3d9c62_generated_image.png',
  'Explosion Proof Speaker': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/5692da4f8_generated_image.png',
  'Anti Noise And Noise Reduction Pavilion': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/084c40246_generated_image.png',
  'Stainless Steel Telephone Booth': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/ce369616a_generated_image.png',
  'Ring Tilt Anti-Collision Device': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/d6338cbab_generated_image.png',
  'Monitoring Device For Lifting Up The Drilling Rig Frame': 'https://media.base44.com/images/public/69e23eba8ee82f425a263579/991b5664c_generated_image.png',
};
